services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  web:
    image: python:3.12-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python app.py"
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - backend
  
  celery:
    image: python:3.12-slim
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install celery redis && celery -A tasks worker --loglevel=info"
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend: